name: 'Move Build Files To Artifacts'
description: 'Move Build Files To Artifacts'

runs:
  using: 'composite'
  steps:

    - name:  Move Build Files To Artifacts
      shell: bash
      run: |
        mkdir -p ./artifacts
        sudo chmod 777 ./artifacts
        cp -r build/* ./artifacts
        ls -lR ./artifacts