name: 'MacOS Release'
description: 'Archive the macOS build files, rename the zip file, create a GitHub release, and upload the asset.'
runs:
  using: 'composite'

  steps:
    - name: Archive macOS Build Files
      shell: bash
      run: |
        # Navigate to the build directory
        cd build/macos/Build/Products/Release

        # Create a zip archive of all files in the Release directory
        zip -r macos-build-${{ inputs.arch }}.zip .

    - name: Rename macOS Build File
      shell: bash
      run: |
        # Rename the zip file to include the tag name and architecture
        mv build/macos/Build/Products/Release/macos-build-${{ inputs.arch }}.zip build/macos/Build/Products/Release/macos-build-${{ inputs.arch }}-${{ inputs.tag_name }}.zip

    - name: Create macOS Release
      id: create_macos_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }} # Use the input instead of secrets.GITHUB_TOKEN
      with:
        tag_name: ${{ inputs.tag_name }}
        release_name: "${{ inputs.release_name }}"
        body: "${{ inputs.release_body }}"
        draft: false
        prerelease: false

    - name: Upload macOS Release Asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.tag_name }}
        files: build/macos/Build/Products/Release/macos-build-${{ inputs.arch }}-${{ inputs.tag_name }}.zip

# Define action inputs
inputs:
  tag_name:
    description: 'The name of the tag'
    required: true
  release_name:
    description: 'The title of the release'
    required: true
  release_body:
    description: 'The body/description of the release'
    required: true
  github_token:
    description: 'The GitHub token for creating the release'
    required: true
  arch:
    description: 'The CPU architecture (e.g., arm64, amd64)'
    required: true