name: 'Windows Release'
description: 'Archive the Windows build files, rename the zip file, create a GitHub release, and upload the asset.'
runs:
  using: 'composite'

  steps:
    - name: Archive Windows Build Files
      shell: pwsh
      run: |
        # Navigate to the build directory
        cd build\windows\x64\runner\Release

        # Create a zip archive of all files in the release directory
        Compress-Archive -Path .\* -DestinationPath windows-build.zip

    - name: Rename Windows Build File
      shell: pwsh
      run: |
        # Rename the zip file to include the tag name
        Rename-Item -Path build\windows\x64\runner\Release\windows-build.zip -NewName "windows-build-${{ inputs.tag_name }}.zip"

    - name: Create Windows Release
      id: create_windows_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }} # Use the input instead of secrets.GITHUB_TOKEN
      with:
        tag_name: ${{ inputs.tag_name }}
        release_name: "${{ inputs.release_name }}"
        body: "${{ inputs.release_body }}"
        draft: false
        prerelease: false

    - name: Upload Windows Release Asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.tag_name }}
        files: build\windows\x64\runner\Release\windows-build-${{ inputs.tag_name }}.zip

# Define action inputs
inputs:
  tag_name:
    description: 'The name of the tag'
    required: true
  release_name:
    description: 'The title of the release'
    required: true
  release_body:
    description: 'The body/description of the release'
    required: true
  github_token:
    description: 'The GitHub token for creating the release'
    required: true