name: 'Prepare Tag Metadata'
description: 'Extract tag details and write the tag message to a file.'
inputs:
  github_ref:
    description: 'The full tag reference (e.g., refs/tags/v1.0.0)'
    required: true
outputs:
  tag_name:
    description: 'The name of the tag'
    value: ${{ steps.extract_and_prepare.outputs.tag_name }}
  release_body:
    description: 'The path to the file containing the tag message'
    value: ${{ steps.extract_and_prepare.outputs.release_body }}
runs:
  using: 'composite'
  steps:
    - name: Extract tag name and prepare tag message
      id: extract_and_prepare
      shell: bash
      run: |
        # Extract tag name
        TAG_NAME=${GITHUB_REF#refs/tags/}
        echo "Extracted tag name: $TAG_NAME"
        echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
        
        # Get the tag message
        TAG_MESSAGE=$(git tag -l --format='%(contents)' $TAG_NAME)
        
        # Write the tag message to a file (optional, if you still need the file)
        TAG_MESSAGE_FILE="tag_message.txt"
        echo "$TAG_MESSAGE" > $TAG_MESSAGE_FILE
        echo "Tag message written to: $TAG_MESSAGE_FILE"
        echo "tag_message_file=$TAG_MESSAGE_FILE" >> $GITHUB_OUTPUT
        
        # Set the release body as an output
        echo "release_body<<EOF" >> $GITHUB_OUTPUT
        echo "$TAG_MESSAGE" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT