name: 'Add Daemon Files To Artifacts'
description: 'Add Daemon Files To Artifacts And Create Zip File For Upload'

inputs:
  tag_name:
    description: 'The name of the tag'
    required: true
  arch:
    description: 'The CPU architecture (e.g., arm64, x64)'
    required: true

outputs:
  file_name:
    description: 'The name of the zip file that must be attached to release.'
    value: ${{ steps.archive_linux_build.outputs.file_name }}

runs:
  using: 'composite'
  steps:

    - name: Fetch and Extract Files
      shell: bash
      run: |
        curl -L -o file.tar.gz ${{ env.LINUX_ASSETS_URL }}
        mkdir -p ./artifacts/linux/${{ inputs.arch }}/release/bundle/lib/src/core/native_resources/linux/
        tar -xvzf file.tar.gz --strip-components=1 -C ./artifacts/linux/${{ inputs.arch }}/release/bundle/lib/src/core/native_resources/linux/

    - name: Archive Linux Build Files
      id: archive_linux_build
      shell: bash
      run: |
        # Navigate to the directory contains built app and daemon files
        cd ./artifacts/linux/${{ inputs.arch }}/release/bundle
        
        # Create a zip archive with the correct file name
        FILE_NAME="linux-build-${{ inputs.arch }}-${{ inputs.tag_name }}.zip"
        zip -r "${FILE_NAME}" .
        
        # Set the file name as an output
        echo "file_name=${FILE_NAME}" >> $GITHUB_OUTPUT
