name: 'Validate Asset Files'
description: 'Validate generated asset files.'
runs:
  using: 'composite'
  steps:
    - name: Validate Asset Files
      shell: bash
      run: |
        # Check if there are changes after generating asset files
        git diff --exit-code lib/src/core/utils/gen/assets || (
          echo "Error: Asset files are outdated. Run the generation command and commit the changes.";
          exit 1;
        )