name: 'Generate Release Download Links'
description: 'Prepare download and release links.'
inputs:
  tag_name:
    description: 'The name of the tag'
    required: true
  file_name:
    description: 'The name of the archived file'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Prepare Download and Release Links
      id: prepare_links
      shell: bash
      run: |
        # Construct download and release links
        DOWNLOAD_LINK="https://github.com/${{ github.repository }}/releases/download/${{ inputs.tag_name }}/${{ inputs.file_name }}"
        RELEASE_LINK="https://github.com/${{ github.repository }}/releases/tag/${{ inputs.tag_name }}"

        # Set the links as outputs
        echo "download_link=${DOWNLOAD_LINK}" >> $GITHUB_OUTPUT
        echo "release_link=${RELEASE_LINK}" >> $GITHUB_OUTPUT

outputs:
  download_link:
    description: 'The download link for the release'
    value: ${{ steps.prepare_links.outputs.download_link }}
  release_link:
    description: 'The release link'
    value: ${{ steps.prepare_links.outputs.release_link }}