name: 'Upload Linux Release Assets'
description: 'Create a GitHub release, and upload the asset for Linux.'
runs:
  using: 'composite'

  steps:
    - name: Create Linux Release
      id: create_linux_release
      uses: softprops/action-gh-release@v2
      continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        tag_name: ${{ inputs.tag_name }}
        body: "${{ inputs.release_body }}"
        draft: false
        prerelease: false
        generate_release_notes: true

    - name: Upload Linux Release Asset
      id: upload_linux_release_asset
      uses: softprops/action-gh-release@v2
      continue-on-error: true
      with:
        tag_name: ${{ inputs.tag_name }}
        files: ./artifacts/linux/${{ inputs.arch }}/release/bundle/${{ inputs.file_name }}

inputs:
  tag_name:
    description: 'The name of the tag'
    required: true
  release_name:
    description: 'The title of the release'
    required: true
  release_body:
    description: 'The body/description of the release'
    required: true
  github_token:
    description: 'The GitHub token for creating the release'
    required: true
  file_name:
    description: 'The name of the asset file, that must be uploaded/attached to the release.'
    required: true
  arch:
    description: 'The CPU architecture (e.g., arm64, x64)'
    required: true
