name: 'Build macOS Release Artifacts'
description: 'Build macOS Application'

inputs:
  tag_name:
    description: 'The name of the tag'
    required: true
  arch:
    description: 'The CPU architecture (e.g., arm64, amd64)'
    required: true

outputs:
  file_name:
    description: 'The name of the zip file that created from build directory.'
    value: ${{ steps.archive_macos_build.outputs.file_name }}

runs:
  using: 'composite'
  steps:
    - name: Enable macOS desktop
      shell: bash
      run: |
        flutter config --enable-macos-desktop

    - name: Fetch and Extract Files
      shell: bash
      run: |
        curl -L -o file.tar.gz ${{ env.MACOS_ASSETS_URL }}
        mkdir -p build/macos/Build/Products/Release/lib/src/core/native_resources/macos/
        tar -xvzf file.tar.gz --strip-components=1 -C build/macos/Build/Products/Release/lib/src/core/native_resources/macos/

    - name: Build application
      shell: bash
      run: |
        flutter build macos --release

    - name: Archive macOS Build Files
      id: archive_macos_build
      shell: bash
      run: |
        # Navigate to the build directory
        cd build/macos/Build/Products/Release
        
        # Create a zip archive with the correct file name
        FILE_NAME="macos-build-${{ inputs.arch }}-${{ inputs.tag_name }}.zip"
        zip -r "${FILE_NAME}" .
        
        # Set the file name as an output
        echo "file_name=${FILE_NAME}" >> $GITHUB_OUTPUT