name: 'Install macOS Build Dependencies'
description: 'Install macOS dependencies'
runs:
  using: 'composite'
  steps:
    - name: Install macOS dependencies
      shell: bash
      run: |
        # Install Homebrew (if not already installed)
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

        # Install required dependencies
        brew install cmake pkg-config ninja
        brew install unzip