name: 'Fetch and Extract Files'
description: 'Fetch and Extract Files'
runs:
  using: 'composite'
  steps:
    - name: Fetch and Extract Files
      shell: bash
      run: |
        curl -L -o file.tar.gz ${{ env.LINUX_ASSETS_URL }}
        mkdir -p lib/src/core/native_resources/linux/
        tar -xzf file.tar.gz --strip-components=1 -C lib/src/core/native_resources/linux/
