name: 'Fetch and Extract Files'
description: 'Fetch and Extract Files'
runs:
  using: 'composite'
  steps:
    - name: Fetch and Extract Files
      shell: bash
      run: |
        curl -L -o file.tar.gz ${{ inputs.assets_url }}
        mkdir -p lib/src/core/native_resources/macos/
        tar -xzf file.tar.gz --strip-components=1 -C lib/src/core/native_resources/macos/

# Define action inputs
inputs:
  assets_url:
    description: 'The URL to fetch the assets from'
    required: true