name: 'Install Linux Build Dependencies (AMD64)'
description: 'Install Linux (AMD64)  dependencies'
runs:
  using: 'composite'
  steps:
    - name: Install Linux (AMD64) dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ninja-build libgtk-3-dev
        sudo apt-get install -y cmake pkg-config
        sudo apt-get install -y libblkid-dev
        sudo apt-get install -y liblzma-dev
        sudo apt-get install -y unzip
