name: 'Linux Release'
description: 'Archive the Linux build files, rename the zip file, create a GitHub release, and upload the asset.'
runs:
  using: 'composite'

  steps:
    - name: Archive Linux Build Files
      shell: bash
      run: |
        # Navigate to the build directory
        cd build/linux/x64/release/bundle

        # Create a zip archive of all files in the bundle directory
        zip -r linux-build.zip .

    - name: Rename Linux Build File
      shell: bash
      run: |
        # Rename the zip file to include the tag name
        mv build/linux/x64/release/bundle/linux-build.zip build/linux/x64/release/bundle/linux-build-${{ inputs.tag_name }}.zip

    - name: Create Linux Release
      id: create_linux_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }} # Use the input instead of secrets.GITHUB_TOKEN
      with:
        tag_name: ${{ inputs.tag_name }}
        release_name: "${{ inputs.release_name }}"
        body: "${{ inputs.release_body }}"
        draft: false
        prerelease: false

    - name: Upload Linux Release Asset
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ inputs.tag_name }}
        files: build/linux/x64/release/bundle/linux-build-${{ inputs.tag_name }}.zip

# Define action inputs
inputs:
  tag_name:
    description: 'The name of the tag'
    required: true
  release_name:
    description: 'The title of the release'
    required: true
  release_body:
    description: 'The body/description of the release'
    required: true
  github_token:
    description: 'The GitHub token for creating the release'
    required: true