name: 'Build Linux ARM64 Artifacts'
description: 'Build Linux Artifacts in ARM64 Container'


runs:
  using: 'composite'
  steps:

  - name: Set up QEMU
    uses: docker/setup-qemu-action@v2

  - name: Run Pipeline in ARM64 Container
    shell: bash
    run: |
      docker run --rm --platform linux/arm64 \
        -v $(pwd)/build:/app/build \
        -v $(pwd):/app -w /app \
        arm64v8/ubuntu:22.04 \
        /bin/bash -c '
        set -ex
      
        # ======== Install Dependencies ========
        apt-get update -y
        apt-get install -y \
          ninja-build libgtk-3-dev cmake pkg-config \
          clang cmake ninja-build libgtk-3-dev pkg-config \
          libblkid-dev liblzma-dev unzip curl git \
          xz-utils libglu1-mesa build-essential \
          gcc-aarch64-linux-gnu g++-aarch64-linux-gnu libc6-dev-arm64-cross
      
        # Define local variables
        export CC=aarch64-linux-gnu-gcc
        export CXX=aarch64-linux-gnu-g++
        export CMAKE_C_COMPILER=aarch64-linux-gnu-gcc
        export CMAKE_CXX_COMPILER=aarch64-linux-gnu-g++
      
        # ======== Install Flutter ========
        git clone https://github.com/flutter/flutter.git -b stable --depth 1 /flutter
        export PATH="/flutter/bin:$PATH"
        flutter --version
      
        # ======== Generating Localization (Before Building App) ========
        echo "=== 1. Generating Localization ==="
        flutter pub get
        dart run build_runner build --delete-conflicting-outputs
        flutter gen-l10n --output-dir=lib/l10n --arb-dir=lib/l10n 2>&1 | tee l10n_output.log
        grep -q "untranslated message" l10n_output.log && { echo "::error::Untranslated messages!"; exit 1; }
        dart lib/src/core/utils/gen/localization/translations_utils.dart
      
        # ======== Generating Assets (Before Building App) ========
        echo "=== 2. Generating Assets ==="
        dart run build_runner build --delete-conflicting-outputs --build-filter="lib/src/core/utils/gen/assets/*.dart" || exit 1
        flutter pub get
        # ======== Building App ========
        echo "=== 3. Building App ==="
        flutter build linux --release --target-platform linux-arm64
        ls -lR build/linux/arm64/release/bundle
        '