name: 'Debugging Logger'
description: 'Display Debug Logs'

inputs:
  subject:
    description: 'subject need debug (e.g , ls)'
    required: true

runs:
  using: 'composite'
  steps:

    - name:  Debugging Logs
      shell: bash
      run: |
        echo "===== Debugging Logs ====="
        echo "== subject: ${{ inputs.subject }} =="
        ${{ inputs.subject }}

# How to use it ?
# see example:
#
#        - name:  Debugging Logs
#          uses: ./.github/actions/utils/debugging-logger
#          with:
#            subject: ls -lR ./build
