name: Linux Release Build

# Add environment variables at the top level
env:
  LINUX_ASSETS_URL: "https://github.com/pactus-project/pactus/releases/download/v1.6.4/pactus-cli_1.6.4_linux_amd64.tar.gz"

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.2.3

jobs:
  build-and-release-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Tag Details
        id: extract_tag
        uses: ./.github/actions/extract-tag-details

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: 'stable'
          cache: true

      - name: Install Linux dependencies
        uses: ./.github/actions/linux-install-dependencies

      - name: Enable Linux desktop
        run: flutter config --enable-linux-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Generate Localization Files
        uses: ./.github/actions/generate-localization

      - name: Generate Asset Files
        uses: ./.github/actions/generate-assets

      - name: Generate some files by build runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Rearrange Code Style
        run: dart format .

      - name: Run Flutter Analyze
        run: flutter analyze

      - name: Fetch and Extract Files
        uses: ./.github/actions/linux-extract-files

      - name: Build application
        run: flutter build linux --release

      - name: Linux Release
        uses: ./.github/actions/linux-release
        with:
          tag_name: ${{ env.tag_name }}
          release_name: "${{ env.title }}"
          release_body: "${{ env.description }}"
          github_token: ${{ secrets.GITHUB_TOKEN }} # Pass the secret as an input
