name: Linux Release Build (AMD64 + Healthy AppImage)

on:
  push:
    tags:
      - 'v*'

# Add environment variables at the top level
env:
  LINUX_ASSETS_URL: "https://github.com/pactus-project/pactus/releases/download/v1.7.1/pactus-cli_1.7.1_linux_amd64.tar.gz"

permissions:
  contents: write


jobs:
  build-and-release-linux-amd64:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: 'stable'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y libfuse2 build-essential patchelf wget zsync squashfs-tools \
            libgtk-3-dev libglib2.0-dev libnss3 libxss1 libasound2 libx11-dev

      - name: Install Flutter Project Dependencies
        uses: ./.github/actions/utils/install-flutter-dependencies


      - name: Build Flutter Linux Bundle
        run: flutter build linux

      - name: Prepare AppDir and Collect Files
        run: |
          mkdir -p AppDir/usr/bin

          # Copy built Flutter bundle
          cp -r build/linux/x64/release/bundle/* AppDir/usr/bin/

          # Copy your .desktop and icon files
          cp linux/pactus_gui.desktop AppDir/
          cp linux/pactus_gui.png AppDir/

          # Create AppRun
          cat <<'EOF' > AppDir/AppRun
          #!/bin/bash
          HERE="$(dirname "$(readlink -f "$0")")"
          exec "$HERE/usr/bin/pactus_gui" "$@"
          EOF

          chmod +x AppDir/AppRun


      - name: Download AppImage Tools
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage -O linuxdeploy
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool
          chmod +x linuxdeploy appimagetool

      - name: Build AppImage
        run: |
          ./linuxdeploy --appdir AppDir --desktop-file AppDir/pactus_gui.desktop --icon-file AppDir/pactus_gui.png --output appimage
          chmod +x ./*.AppImage

      - name: Test AppImage (headless)
        run: |
          ./pactus_gui*.AppImage --appimage-extract
          chmod +x squashfs-root/AppRun
          squashfs-root/AppRun --help || echo "✅ AppRun executed (GUI not launched in CI, but it's working)"

      - name: Upload Built AppImage
        uses: actions/upload-artifact@v4
        with:
          name: PactusGUI-AppImage
          path: ./*.AppImage
