name: Linux Release Build

# Add environment variables at the top level
env:
  LINUX_ASSETS_URL: "https://github.com/pactus-project/pactus/releases/download/v1.7.1/pactus-cli_1.7.1_linux_amd64.tar.gz"

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.2.3

jobs:
  build-and-release-linux:
    runs-on: ubuntu-latest

    outputs:
      tag_name: ${{ steps.get_tag_details.outputs.tag_name }}
      release_body: ${{ steps.get_tag_details.outputs.release_body }}
      file_name: ${{ steps.build_linux_app.outputs.file_name }}
      download_link: ${{ steps.prepare_download_links.outputs.download_link }}
      release_link: ${{ steps.prepare_download_links.outputs.release_link }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: 'stable'
          cache: true

      - name: Install Flutter Project Dependencies
        uses: ./.github/actions/utils/install-flutter-dependencies

      - name: Install Linux Build Dependencies
        uses: ./.github/actions/linux/install-dependencies

      - name: Prepare Tag Metadata
        id: get_tag_details
        uses: ./.github/actions/utils/extract-tag-metadata
        with:
          github_ref: ${{ github.ref }}

      - name: Build Linux Release Artifacts
        id: build_linux_app
        uses: ./.github/actions/linux/build-artifacts
        with:
          tag_name: ${{ steps.get_tag_details.outputs.tag_name }}

      - name: Upload Linux Release Assets
        uses: ./.github/actions/linux/release
        with:
          tag_name: ${{ steps.get_tag_details.outputs.tag_name }}
          release_name: ${{ steps.get_tag_details.outputs.tag_name }}
          release_body: ${{ steps.get_tag_details.outputs.release_body }}
          file_name: ${{ steps.build_linux_app.outputs.file_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Release Download Links
        id: prepare_download_links
        uses: ./.github/actions/utils/generate-download-links
        with:
          tag_name: ${{ steps.get_tag_details.outputs.tag_name }}
          file_name: ${{ steps.build_linux_app.outputs.file_name }}

  notify-linux:
    needs: build-and-release-linux
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: |
            🚀 **GUI Release:** [${{ needs.build-and-release-linux.outputs.tag_name }}](${{ needs.build-and-release-linux.outputs.release_link }})  📥[Download Linux Version](${{ needs.build-and-release-linux.outputs.download_link }})

      - name: Send Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: |
            🚀 **GUI Release:** [${{ needs.build-and-release-linux.outputs.tag_name }}](${{ needs.build-and-release-linux.outputs.release_link }})      📥[Download Linux Version](${{ needs.build-and-release-linux.outputs.download_link }})
