name: MacOS Release Build (AMD64)

# Add environment variables at the top level
env:
  MACOS_ASSETS_URL: "https://github.com/pactus-project/pactus/releases/download/v1.6.4/pactus-cli_1.6.4_darwin_amd64.tar.gz"

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.2.3

jobs:
  build-and-release-macos:
    runs-on: macos-latest
    outputs:
      release_tag: macos-amd64-release-${{ github.run_number }}
      platform: macOS
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Tag Details
        id: extract_tag
        uses: ./.github/actions/extract-tag-details

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: 'stable'
          cache: true

      - name: Install macOS dependencies
        uses: ./.github/actions/macos-install-dependencies

      - name: Enable macOS desktop
        run: flutter config --enable-macos-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Generate Localization Files
        uses: ./.github/actions/generate-localization

      - name: Generate Asset Files
        uses: ./.github/actions/generate-assets

      - name: Generate some files by build runner
        run: dart run build_runner build --delete-conflicting-outputs

      - name: Rearrange Code Style
        run: dart format .

      - name: Run Flutter Analyze
        run: flutter analyze

      - name: Fetch and Extract Files
        uses: ./.github/actions/macos-extract-files
        with:
          assets_url: ${{ env.MACOS_ASSETS_URL }}

      - name: Build application
        run: flutter build macos --release

      - name: macOS Release
        uses: ./.github/actions/macos-release
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "${{ steps.extract_tag.outputs.title }}"
          release_body: "${{ steps.extract_tag.outputs.description }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          arch: amd64
